# # # # # # # # # # # # # # # # # # # #
# SimpleChatFormat configuration
#

# Indicates whether players need a permission to use color codes in the chat.
NeedsPermissionForColors: false

# Specifies the chat format to use. Color codes are available.
# In addition you may use the following placeholders:
# {prefix} -> prints all prefixes found for a player
# {suffix} -> prints all suffixes found for a player
# {world} -> prints the world name where the player is in
# {name} -> prints the player's display name
# {message} prints the actual message
Format: "{prefix} {name} {suffix} : {message}"