name: SimpleChatFormat
description: Use colors in the chat and display meta information from Vault.
version: @version@
author: Axel Rindle
main: de.axelrindle.simplechatformat.SimpleChatFormat
depend: [ Vault ]
website: https://dev.bukkit.org/projects/simplechatformat-plugin
commands:
  simplechatformat:
    description: Admin access.
    usage: /simplechatformat
    permission: simplechatformat.manage
    aliases:
      - scf